# Proves assets\ui\ui-palette.json and assets\ui\ui-screens.json still agree with
# the art they were measured from.
#
#   powershell -NoProfile -File tools\check-ui-data.ps1
#
# WHY THIS EXISTS
#
# ui-atlas.json is generated by tools\extract-ui-spec.ps1 and its `-Check` fails
# the moment the file and the art disagree. The other two are hand-measured -
# about 118 KB of numbers with nothing keeping them honest. Two of them are
# currently records of real bugs in tools\make-hud-sheet.ps1 (our crafting and
# furnace slots sit one pixel left of the reference; our double chest is two
# pixels short). The day somebody fixes that script and rebuilds the sheet, both
# files quietly become wrong and nothing says so. This is what says so.
#
# It does NOT regenerate anything. Validating recorded numbers against the art is
# the whole job: re-open the image, re-read the pixel, compare.
#
#   palette   every entry's source.file is re-opened and the pixel at its `at` is
#             compared to its `hex`. rect_mean entries carry a rect and are
#             re-averaged. `measured: false` rows are documented constants with
#             no art source and are skipped by name. One row is flagged
#             `reproducible: false` and is reported as such rather than passed.
#
#   screens   every recorded cell is checked at the two corners that define a
#             slot - the frame's top-left must be the dark bevel and (+17,+17)
#             must be #FFFFFF - and every panel is checked against the measured
#             bounding box of the art. Regions the sheet genuinely does not draw
#             carry `drawn: false` and say why.
#
#   ours      the same, against assets/textures/hud.png, plus the check that
#             would have caught the missing `indicators` strip: every opaque row
#             of the sheet must fall inside some recorded strip.
#
#   joins     atlas_id is the one key between the three files. Every one must
#             exist in the atlas, and where both sides record a size they must
#             agree.
#
# EXIT CODE. 0 and one line when everything passes. 1 and a list naming each
# failure, what was expected and what was found, when it does not.

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Drawing

$root = Split-Path -Parent $PSScriptRoot
$failures = New-Object System.Collections.Generic.List[string]
$warnings = New-Object System.Collections.Generic.List[string]

function Add-Failure { param([string]$Message) $failures.Add($Message) | Out-Null }
function Add-Warning { param([string]$Message) $warnings.Add($Message) | Out-Null }

function Read-Json {
    param([string]$Relative)
    $path = Join-Path $root $Relative
    if (-not (Test-Path -LiteralPath $path)) { throw "Missing $Relative at $path" }
    return ([System.IO.File]::ReadAllText($path) | ConvertFrom-Json)
}

# One image, unpacked once into a byte array. GetPixel is fine for the palette's
# handful of reads per file, but a cell sweep is 1,514 slots and a bounding box
# is a quarter of a million pixels, and GetPixel is far too slow for that.
function Open-Image {
    param([string]$Path)
    $bitmap = [System.Drawing.Bitmap]::FromFile((Resolve-Path -LiteralPath $Path))
    try {
        $rect = New-Object System.Drawing.Rectangle 0, 0, $bitmap.Width, $bitmap.Height
        $data = $bitmap.LockBits($rect, [System.Drawing.Imaging.ImageLockMode]::ReadOnly,
            [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
        $length = [Math]::Abs($data.Stride) * $bitmap.Height
        $buffer = New-Object byte[] $length
        [System.Runtime.InteropServices.Marshal]::Copy($data.Scan0, $buffer, 0, $length)
        $bitmap.UnlockBits($data)
        return [PSCustomObject]@{
            Path = $Path; Width = $bitmap.Width; Height = $bitmap.Height
            Stride = $data.Stride; Buffer = $buffer
        }
    } finally { $bitmap.Dispose() }
}

function Get-Hex {
    param($Image, [int]$X, [int]$Y, [switch]$WithAlpha)
    if ($X -lt 0 -or $Y -lt 0 -or $X -ge $Image.Width -or $Y -ge $Image.Height) { return '#OUTSIDE' }
    $i = $Y * $Image.Stride + $X * 4
    if ($WithAlpha) {
        return '#{0:X2}{1:X2}{2:X2}{3:X2}' -f $Image.Buffer[$i + 2], $Image.Buffer[$i + 1], $Image.Buffer[$i], $Image.Buffer[$i + 3]
    }
    return '#{0:X2}{1:X2}{2:X2}' -f $Image.Buffer[$i + 2], $Image.Buffer[$i + 1], $Image.Buffer[$i]
}

function Get-Alpha {
    param($Image, [int]$X, [int]$Y)
    return $Image.Buffer[$Y * $Image.Stride + $X * 4 + 3]
}

# The bounding box of everything that is not fully transparent, in the window
# given. Returns $null when the window is empty.
function Get-OpaqueBox {
    param($Image, [int]$X, [int]$Y, [int]$W, [int]$H)
    $minX = [int]::MaxValue; $minY = [int]::MaxValue; $maxX = -1; $maxY = -1
    for ($yy = $Y; $yy -lt $Y + $H; $yy++) {
        $rowBase = $yy * $Image.Stride
        for ($xx = $X; $xx -lt $X + $W; $xx++) {
            if ($Image.Buffer[$rowBase + $xx * 4 + 3] -ne 0) {
                if ($xx -lt $minX) { $minX = $xx }
                if ($xx -gt $maxX) { $maxX = $xx }
                if ($yy -lt $minY) { $minY = $yy }
                if ($yy -gt $maxY) { $maxY = $yy }
            }
        }
    }
    if ($maxX -lt 0) { return $null }
    return [PSCustomObject]@{ X = $minX; Y = $minY; W = $maxX - $minX + 1; H = $maxY - $minY + 1 }
}

# Same idea, but "drawn" means "not the panel grey" - used to find the spent
# furnace indicators, which are painted onto an opaque panel and so have no
# transparency to bound them.
function Get-NonFillBox {
    param($Image, [int]$X, [int]$Y, [int]$W, [int]$H, [string]$Fill)
    $minX = [int]::MaxValue; $minY = [int]::MaxValue; $maxX = -1; $maxY = -1
    for ($yy = $Y; $yy -lt $Y + $H; $yy++) {
        for ($xx = $X; $xx -lt $X + $W; $xx++) {
            if ((Get-Hex $Image $xx $yy) -ne $Fill) {
                if ($xx -lt $minX) { $minX = $xx }
                if ($xx -gt $maxX) { $maxX = $xx }
                if ($yy -lt $minY) { $minY = $yy }
                if ($yy -gt $maxY) { $maxY = $yy }
            }
        }
    }
    if ($maxX -lt 0) { return $null }
    return [PSCustomObject]@{ X = $minX; Y = $minY; W = $maxX - $minX + 1; H = $maxY - $minY + 1 }
}

function Format-Box { param($Box) if ($null -eq $Box) { 'empty' } else { '({0},{1}) {2}x{3}' -f $Box.X, $Box.Y, $Box.W, $Box.H } }

$atlas = Read-Json 'assets\ui\ui-atlas.json'
$palette = Read-Json 'assets\ui\ui-palette.json'
$screens = Read-Json 'assets\ui\ui-screens.json'

$atlasSprites = @{}
foreach ($group in $atlas.groups) {
    foreach ($sprite in $group.sprites) { $atlasSprites[$sprite.id] = $sprite }
}

function Resolve-Root {
    param($RootMap, [string]$Name, [string]$File, [string]$Where)
    if (-not $RootMap.ContainsKey($Name)) {
        Add-Failure "$Where names root '$Name', which is not in the roots map"
        return $null
    }
    $joined = $RootMap[$Name] + '/' + $File
    return (Join-Path $root ($joined -replace '/', '\'))
}

# ---------------------------------------------------------------------------
# Joins. atlas_id is the only key between the three files; a dead one is worse
# than none, because it looks like a cross-check and is not.
# ---------------------------------------------------------------------------
$paletteRoots = @{}
$palette.roots.PSObject.Properties | ForEach-Object { $paletteRoots[$_.Name] = $_.Value }
$screenRoots = @{}
$screens.roots.PSObject.Properties | ForEach-Object { $screenRoots[$_.Name] = $_.Value }

foreach ($name in $screenRoots.Keys) {
    if ($paletteRoots.ContainsKey($name) -and $paletteRoots[$name] -ne $screenRoots[$name]) {
        Add-Failure ("roots.{0} disagrees between the files: ui-screens.json has '{1}', ui-palette.json has '{2}'" -f
            $name, $screenRoots[$name], $paletteRoots[$name])
    }
}
foreach ($name in $screenRoots.Keys) {
    $dir = Join-Path $root ($screenRoots[$name] -replace '/', '\')
    if (-not (Test-Path -LiteralPath $dir)) { Add-Failure "roots.$name points at $dir, which does not exist" }
}

$joinCount = 0
$paletteEntries = New-Object System.Collections.Generic.List[object]
foreach ($groupName in $palette.groups.PSObject.Properties.Name) {
    foreach ($entry in $palette.groups.$groupName) {
        $entry | Add-Member -NotePropertyName '_group' -NotePropertyValue $groupName -Force
        $paletteEntries.Add($entry) | Out-Null
    }
}
foreach ($entry in $paletteEntries) {
    if ($entry.atlas_id) {
        $joinCount++
        if (-not $atlasSprites.ContainsKey($entry.atlas_id)) {
            Add-Failure "palette $($entry.id): atlas_id '$($entry.atlas_id)' is in no group of ui-atlas.json"
        }
    }
}
foreach ($screen in $screens.screens) {
    if (-not $screen.atlas_id) {
        Add-Failure "screen $($screen.id) has no atlas_id, so nothing joins it to ui-atlas.json"
        continue
    }
    $joinCount++
    $sprite = $atlasSprites[$screen.atlas_id]
    if ($null -eq $sprite) {
        Add-Failure "screen $($screen.id): atlas_id '$($screen.atlas_id)' is in no group of ui-atlas.json"
        continue
    }
    if ($screen.file_size) {
        $w = [int]$screen.file_size[0]; $h = [int]$screen.file_size[1]
        if ($sprite.width -ne $w -or $sprite.height -ne $h) {
            Add-Failure ("screen {0}: file_size is [{1}, {2}] but the atlas measured {3}x{4} for {5}" -f
                $screen.id, $w, $h, $sprite.width, $sprite.height, $screen.atlas_id)
        }
    }
}
foreach ($id in @($screens.cell.atlas_id) + @($screens.panel.atlas_id) + @($screens.cell.highlight.atlas_ids)) {
    if ($id) {
        $joinCount++
        if (-not $atlasSprites.ContainsKey($id)) { Add-Failure "ui-screens.json references atlas_id '$id', which the atlas does not have" }
    }
}
$slotSprite = $atlasSprites[$screens.cell.atlas_id]
if ($slotSprite -and ($slotSprite.width -ne [int]$screens.cell.frame_size[0] -or $slotSprite.height -ne [int]$screens.cell.frame_size[1])) {
    Add-Failure ("cell.frame_size is [{0}, {1}] but the atlas measured {2}x{3} for {4}" -f
        $screens.cell.frame_size[0], $screens.cell.frame_size[1], $slotSprite.width, $slotSprite.height, $screens.cell.atlas_id)
}
foreach ($id in $screens.cell.highlight.atlas_ids) {
    $sprite = $atlasSprites[$id]
    if ($sprite -and ($sprite.width -ne [int]$screens.cell.highlight.size[0] -or $sprite.height -ne [int]$screens.cell.highlight.size[1])) {
        Add-Failure ("cell.highlight.size is [{0}, {1}] but the atlas measured {2}x{3} for {4}" -f
            $screens.cell.highlight.size[0], $screens.cell.highlight.size[1], $sprite.width, $sprite.height, $id)
    }
}

# ---------------------------------------------------------------------------
# Palette. Re-open, re-read, compare.
# ---------------------------------------------------------------------------
$paletteOk = 0; $paletteDocumented = 0; $paletteUnreproducible = 0; $paletteRectMean = 0
$byFile = @{}
foreach ($entry in $paletteEntries) {
    if (-not $entry.measured) { $paletteDocumented++; continue }
    if ($entry.PSObject.Properties.Name -contains 'reproducible' -and -not $entry.reproducible) {
        $paletteUnreproducible++
        Add-Warning ("palette {0}: declared not reproducible - {1}" -f $entry.id,
            (($entry.reproducibility_note -split '\. ')[0] + '.'))
        continue
    }
    $key = $entry.source.root + '|' + $entry.source.file
    if (-not $byFile.ContainsKey($key)) { $byFile[$key] = New-Object System.Collections.Generic.List[object] }
    $byFile[$key].Add($entry) | Out-Null
}

foreach ($key in ($byFile.Keys | Sort-Object)) {
    $parts = $key -split '\|', 2
    $path = Resolve-Root $paletteRoots $parts[0] $parts[1] "palette entries on $($parts[1])"
    if ($null -eq $path) { continue }
    if (-not (Test-Path -LiteralPath $path)) {
        foreach ($entry in $byFile[$key]) { Add-Failure "palette $($entry.id): source file not found at $path" }
        continue
    }
    $bitmap = [System.Drawing.Bitmap]::FromFile((Resolve-Path -LiteralPath $path))
    try {
        foreach ($entry in $byFile[$key]) {
            if ($entry.method -eq 'rect_mean') {
                if ($null -eq $entry.source.rect) {
                    Add-Failure ("palette {0}: method is rect_mean but no rect is recorded, so nothing can reproduce it. Either add the rect or flag the row `"reproducible`": false with the reason." -f $entry.id)
                    continue
                }
                $rx = [int]$entry.source.rect[0]; $ry = [int]$entry.source.rect[1]
                $rw = [int]$entry.source.rect[2]; $rh = [int]$entry.source.rect[3]
                $sa = 0; $sr = 0; $sg = 0; $sb = 0; $n = 0
                for ($yy = $ry; $yy -lt $ry + $rh; $yy++) {
                    for ($xx = $rx; $xx -lt $rx + $rw; $xx++) {
                        $p = $bitmap.GetPixel($xx, $yy)
                        $sa += $p.A; $sr += $p.R; $sg += $p.G; $sb += $p.B; $n++
                    }
                }
                $found = '#{0:X2}{1:X2}{2:X2}{3:X2}' -f [int][Math]::Round($sr / $n), [int][Math]::Round($sg / $n),
                    [int][Math]::Round($sb / $n), [int][Math]::Round($sa / $n)
                if ($found -ne $entry.hex.ToUpper()) {
                    Add-Failure ("palette {0}: expected {1}, found {2} - mean of [{3},{4},{5},{6}] in {7}" -f
                        $entry.id, $entry.hex, $found, $rx, $ry, $rw, $rh, $entry.source.file)
                } else { $paletteRectMean++ }
                continue
            }
            $ax = [int]$entry.source.at[0]; $ay = [int]$entry.source.at[1]
            if ($ax -lt 0 -or $ay -lt 0 -or $ax -ge $bitmap.Width -or $ay -ge $bitmap.Height) {
                Add-Failure ("palette {0}: at ({1},{2}) is outside {3}, which is {4}x{5}" -f
                    $entry.id, $ax, $ay, $entry.source.file, $bitmap.Width, $bitmap.Height)
                continue
            }
            $p = $bitmap.GetPixel($ax, $ay)
            $found = '#{0:X2}{1:X2}{2:X2}{3:X2}' -f $p.R, $p.G, $p.B, $p.A
            if ($found -ne $entry.hex.ToUpper()) {
                Add-Failure ("palette {0}: expected {1}, found {2} at ({3},{4}) in {5}" -f
                    $entry.id, $entry.hex, $found, $ax, $ay, $entry.source.file)
            } else { $paletteOk++ }
        }
    } finally { $bitmap.Dispose() }
}

# The header used to say "the four rows flagged measured: false" when there were
# seventeen. Counting them here is what stops that happening again.
$counts = $palette.counts
if ($null -eq $counts) {
    Add-Failure 'ui-palette.json has no "counts" block, so its own header numbers are unchecked'
} else {
    $actual = [ordered]@{
        entries = $paletteEntries.Count
        measured = ($paletteEntries | Where-Object { $_.measured }).Count
        documented = $paletteDocumented
        reproducible_by_pixel = ($paletteEntries | Where-Object { $_.measured -and $_.method -ne 'rect_mean' -and -not ($_.PSObject.Properties.Name -contains 'reproducible' -and -not $_.reproducible) }).Count
        reproducible_by_rect_mean = ($paletteEntries | Where-Object { $_.measured -and $_.method -eq 'rect_mean' -and -not ($_.PSObject.Properties.Name -contains 'reproducible' -and -not $_.reproducible) }).Count
        not_reproducible = $paletteUnreproducible
    }
    foreach ($name in $actual.Keys) {
        if ([int]$counts.$name -ne [int]$actual[$name]) {
            Add-Failure ("ui-palette.json counts.{0} says {1}, the entries say {2}" -f $name, $counts.$name, $actual[$name])
        }
    }
    foreach ($method in $counts.by_method.PSObject.Properties.Name) {
        $seen = ($paletteEntries | Where-Object { $_.method -eq $method }).Count
        if ([int]$counts.by_method.$method -ne $seen) {
            Add-Failure ("ui-palette.json counts.by_method.{0} says {1}, the entries say {2}" -f $method, $counts.by_method.$method, $seen)
        }
    }
}

# ---------------------------------------------------------------------------
# Screens. A slot is defined by two corners: the dark bevel at the frame's
# top-left and #FFFFFF at (+17,+17). Checking both is what makes a one-pixel
# shift - the exact bug this project keeps paying for - impossible to miss.
# ---------------------------------------------------------------------------
$lightBevel = $screens.cell.edges.bottom.colour
$defaultDark = $screens.cell.edges.top.colour
$panelFill = $screens.panel.fill

$divergenceIndex = @{}
foreach ($divergence in $screens.ours.known_divergences) {
    foreach ($region in $divergence.regions) { $divergenceIndex[$divergence.screen + '/' + $region] = $divergence }
    $divergenceIndex[$divergence.screen] = $divergence
}

function Test-Cells {
    param($Image, $Screen, $Region, [int]$OffsetX, [int]$OffsetY, [string]$Label)

    if ($null -eq $Region.frame_size) { return 0 }
    if ($Region.PSObject.Properties.Name -contains 'drawn' -and -not $Region.drawn) { return 0 }
    $dark = if ($Region.bevel_dark) { $Region.bevel_dark } else { $defaultDark }
    $size = [int]$Region.frame_size
    $checked = 0
    for ($row = 0; $row -lt [int]$Region.rows; $row++) {
        for ($col = 0; $col -lt [int]$Region.cols; $col++) {
            $fx = $OffsetX + [int]$Region.origin_x - 1 + $col * [int]$Region.pitch_x
            $fy = $OffsetY + [int]$Region.origin_y - 1 + $row * [int]$Region.pitch_y
            $topLeft = Get-Hex $Image $fx $fy
            $bottomRight = Get-Hex $Image ($fx + $size - 1) ($fy + $size - 1)
            $checked++
            if ($topLeft -ne $dark -or $bottomRight -ne $lightBevel) {
                $message = "{0}/{1} cell [{2},{3}]: expected {4} at the frame corner ({5},{6}) and {7} at (+{8},+{8}), found {9} and {10}" -f
                    $Label, $Region.id, $col, $row, $dark, $fx, $fy, $lightBevel, ($size - 1), $topLeft, $bottomRight
                $divergence = $divergenceIndex[$Screen.id + '/' + $Region.id]
                if ($divergence) {
                    $message += " -- DECLARED DIVERGENCE '$($divergence.id)': $($divergence.on_fix)"
                }
                Add-Failure $message
            }
        }
    }
    return $checked
}

$cellsChecked = 0
$screensChecked = 0
$panelImages = @{}

foreach ($screen in $screens.screens) {
    $path = Resolve-Root $screenRoots $screen.root $screen.source "screen $($screen.id)"
    if ($null -eq $path) { continue }
    if (-not (Test-Path -LiteralPath $path)) {
        Add-Failure "screen $($screen.id): $($screen.source) not found at $path"
        continue
    }
    $image = Open-Image $path
    $panelImages[$screen.id] = $image
    $screensChecked++

    if ($screen.file_size -and ($image.Width -ne [int]$screen.file_size[0] -or $image.Height -ne [int]$screen.file_size[1])) {
        Add-Failure ("screen {0}: file_size says [{1}, {2}], the file is {3}x{4}" -f
            $screen.id, $screen.file_size[0], $screen.file_size[1], $image.Width, $image.Height)
    }

    $originX = 0; $originY = 0
    if ($screen.panel_origin_in_file) { $originX = [int]$screen.panel_origin_in_file[0]; $originY = [int]$screen.panel_origin_in_file[1] }

    $box = Get-OpaqueBox $image 0 0 $image.Width $image.Height
    $expected = [PSCustomObject]@{ X = $originX; Y = $originY; W = [int]$screen.panel[0]; H = [int]$screen.panel[1] }
    if ($null -eq $box -or $box.X -ne $expected.X -or $box.Y -ne $expected.Y -or $box.W -ne $expected.W -or $box.H -ne $expected.H) {
        Add-Failure ("screen {0}: panel is recorded as {1} but the drawn art measures {2} in {3}" -f
            $screen.id, (Format-Box $expected), (Format-Box $box), $screen.source)
    }

    foreach ($region in $screen.regions) {
        $cellsChecked += Test-Cells $image $screen $region $originX $originY "screen $($screen.id)"

        if ($region.well) {
            $wx = $originX + [int]$region.well.x
            $wy = $originY + [int]$region.well.y
            $ww = [int]$region.well.w; $wh = [int]$region.well.h
            $wellDark = if ($region.well.outline) { $region.well.outline } else { $defaultDark }
            $wellLight = if ($region.well.outline) { $region.well.outline } else { $lightBevel }
            $topLeft = Get-Hex $image $wx $wy
            $bottomRight = Get-Hex $image ($wx + $ww - 1) ($wy + $wh - 1)
            if ($topLeft -ne $wellDark -or $bottomRight -ne $wellLight) {
                Add-Failure ("screen {0}/{1} well: expected {2} at ({3},{4}) and {5} at the far corner, found {6} and {7}" -f
                    $screen.id, $region.id, $wellDark, $wx, $wy, $wellLight, $topLeft, $bottomRight)
            }
        }
    }
}

# `identical_to` is a claim that two sheets are the same picture. It earns the
# duplicated geometry that follows it, so it is re-proved rather than trusted.
$identityChecks = 0
foreach ($screen in $screens.screens) {
    foreach ($otherId in $screen.identical_to) {
        if ($screen.id -ge $otherId) { continue }
        $other = $screens.screens | Where-Object { $_.id -eq $otherId }
        if ($null -eq $other) { Add-Failure "screen $($screen.id): identical_to names '$otherId', which has no entry"; continue }
        $a = $panelImages[$screen.id]; $b = $panelImages[$otherId]
        if ($null -eq $a -or $null -eq $b) { continue }
        $w = [int]$screen.panel[0]; $h = [int]$screen.panel[1]
        $differing = 0
        for ($y = 0; $y -lt $h; $y++) {
            for ($x = 0; $x -lt $w; $x++) {
                if ((Get-Hex $a $x $y -WithAlpha) -ne (Get-Hex $b $x $y -WithAlpha)) { $differing++ }
            }
        }
        $identityChecks++
        if ($differing -ne 0) {
            Add-Failure ("screen {0} claims to be identical to {1}, but {2} of {3} pixels differ over the {4}x{5} panel" -f
                $screen.id, $otherId, $differing, ($w * $h), $w, $h)
        }
    }
}

# ---------------------------------------------------------------------------
# Ours. Same checks against our own sheet, plus the one that would have caught
# the `indicators` strip going unrecorded for twenty milestones: every opaque
# row of hud.png has to belong to some strip.
# ---------------------------------------------------------------------------
$sheetPath = Resolve-Root $screenRoots $screens.ours.sheet.root $screens.ours.sheet.source 'ours.sheet'
$oursCells = 0
if ($sheetPath -and (Test-Path -LiteralPath $sheetPath)) {
    $sheet = Open-Image $sheetPath
    if ($sheet.Width -ne [int]$screens.ours.sheet.size[0] -or $sheet.Height -ne [int]$screens.ours.sheet.size[1]) {
        Add-Failure ("ours.sheet.size says [{0}, {1}], hud.png is {2}x{3}" -f
            $screens.ours.sheet.size[0], $screens.ours.sheet.size[1], $sheet.Width, $sheet.Height)
    }

    $strips = @{}
    $covered = New-Object bool[] $sheet.Height
    foreach ($strip in $screens.ours.strips) {
        $strips[$strip.id] = $strip
        $y = [int]$strip.y; $h = [int]$strip.h
        if ($y -lt 0 -or $y + $h -gt $sheet.Height) {
            Add-Failure ("ours.strips[{0}] covers rows {1}..{2}, which is off a {3}-row sheet" -f $strip.id, $y, ($y + $h - 1), $sheet.Height)
            continue
        }
        for ($row = $y; $row -lt $y + $h; $row++) { $covered[$row] = $true }
        if ([int]$strip.w -gt $sheet.Width) {
            Add-Failure ("ours.strips[{0}] is {1} wide on a {2}-wide sheet" -f $strip.id, $strip.w, $sheet.Width)
        }
    }

    $uncovered = New-Object System.Collections.Generic.List[string]
    for ($row = 0; $row -lt $sheet.Height; $row++) {
        if ($covered[$row]) { continue }
        $box = Get-OpaqueBox $sheet 0 $row $sheet.Width 1
        if ($null -ne $box) { $uncovered.Add(('row {0} (x {1}..{2})' -f $row, $box.X, ($box.X + $box.W - 1))) | Out-Null }
    }
    if ($uncovered.Count -gt 0) {
        Add-Failure ("hud.png has drawn pixels no strip in ours.strips accounts for: {0}. Real art with no recorded geometry cannot be drawn - add the strip, measured off the sheet." -f ($uncovered -join '; '))
    }

    foreach ($screen in $screens.ours.screens) {
        if (-not $screen.strip) { Add-Failure "ours screen $($screen.id) names no strip"; continue }
        $strip = $strips[$screen.strip]
        if ($null -eq $strip) { Add-Failure "ours screen $($screen.id): strip '$($screen.strip)' is not in ours.strips"; continue }
        $offsetY = [int]$strip.y

        $box = Get-OpaqueBox $sheet 0 $offsetY $sheet.Width ([int]$strip.h)
        $expected = [PSCustomObject]@{ X = 0; Y = $offsetY; W = [int]$screen.panel[0]; H = [int]$screen.panel[1] }
        if ($null -eq $box -or $box.X -ne 0 -or $box.Y -ne $offsetY -or $box.W -ne $expected.W -or $box.H -ne $expected.H) {
            $message = "ours {0}: panel is recorded as {1} but the drawn art in strip '{2}' measures {3}" -f
                $screen.id, (Format-Box $expected), $screen.strip, (Format-Box $box)
            $divergence = $divergenceIndex[$screen.id]
            if ($divergence) { $message += " -- DECLARED DIVERGENCE '$($divergence.id)': $($divergence.on_fix)" }
            Add-Failure $message
        }

        foreach ($region in $screen.regions) {
            $oursCells += Test-Cells $sheet $screen $region 0 $offsetY "ours $($screen.id)"
        }
    }

    # The indicators strip is the one place we record art that is drawn OVER
    # other art, so its rectangles are only right if they still land on the
    # spent indicators baked into the furnace panel.
    foreach ($strip in $screens.ours.strips) {
        foreach ($part in $strip.parts) {
            $box = Get-OpaqueBox $sheet ([int]$part.x) ([int]$part.y) ([int]$part.w) ([int]$part.h)
            $expected = [PSCustomObject]@{ X = [int]$part.opaque.x; Y = [int]$part.opaque.y; W = [int]$part.opaque.w; H = [int]$part.opaque.h }
            if ($null -eq $box -or $box.X -ne $expected.X -or $box.Y -ne $expected.Y -or $box.W -ne $expected.W -or $box.H -ne $expected.H) {
                Add-Failure ("ours.strips[{0}].parts[{1}]: opaque is recorded as {2} but the art in its {3}x{4} cell measures {5}" -f
                    $strip.id, $part.id, (Format-Box $expected), $part.w, $part.h, (Format-Box $box))
                continue
            }
            if ($null -eq $part.draws_over) { continue }
            $target = $screens.ours.screens | Where-Object { $_.id -eq $part.draws_over.screen }
            if ($null -eq $target) { Add-Failure "ours.strips[$($strip.id)].parts[$($part.id)] draws over '$($part.draws_over.screen)', which has no entry"; continue }
            $targetStrip = $strips[$target.strip]
            $tx = [int]$part.draws_over.x
            $ty = [int]$targetStrip.y + [int]$part.draws_over.y
            $spent = Get-NonFillBox $sheet $tx $ty ([int]$part.w) ([int]$part.h) $panelFill
            $wantX = $tx + ($box.X - [int]$part.x)
            $wantY = $ty + ($box.Y - [int]$part.y)
            if ($null -eq $spent -or $spent.X -ne $wantX -or $spent.Y -ne $wantY -or $spent.W -ne $box.W -or $spent.H -ne $box.H) {
                Add-Failure ("ours.strips[{0}].parts[{1}]: drawn at ({2},{3}) on {4} the lit art would cover ({5},{6}) {7}x{8}, but the spent art there measures {9}" -f
                    $strip.id, $part.id, $part.draws_over.x, $part.draws_over.y, $part.draws_over.screen,
                    $wantX, $wantY, $box.W, $box.H, (Format-Box $spent))
            }
        }
    }

    # A divergence that no longer describes the rows it points at is worse than
    # no divergence block: it is a stale excuse the checker would honour.
    foreach ($divergence in $screens.ours.known_divergences) {
        $screen = $screens.ours.screens | Where-Object { $_.id -eq $divergence.screen }
        if ($null -eq $screen) { Add-Failure "known_divergences[$($divergence.id)] names screen '$($divergence.screen)', which has no entry"; continue }
        foreach ($regionId in $divergence.regions) {
            $region = $screen.regions | Where-Object { $_.id -eq $regionId }
            if ($null -eq $region) {
                Add-Failure "known_divergences[$($divergence.id)] names region '$regionId' of $($divergence.screen), which has no entry"
                continue
            }
            $recorded = $divergence.recorded.$regionId
            if ($null -eq $recorded) { continue }
            if ([int]$recorded[0] -ne [int]$region.origin_x -or [int]$recorded[1] -ne [int]$region.origin_y) {
                Add-Failure ("known_divergences[{0}] says {1}/{2} is at ({3},{4}), the region says ({5},{6}) - the divergence has gone stale" -f
                    $divergence.id, $divergence.screen, $regionId, $recorded[0], $recorded[1], $region.origin_x, $region.origin_y)
            }
        }
    }
}

# ---------------------------------------------------------------------------
# Report.
# ---------------------------------------------------------------------------
Write-Host ("  palette   {0} pixels re-read, {1} rect means re-averaged, {2} documented constants skipped, {3} declared unreproducible" -f
    $paletteOk, $paletteRectMean, $paletteDocumented, $paletteUnreproducible)
Write-Host ("  screens   {0} reference screens, {1} cells at both bevel corners, {2} identity comparisons" -f
    $screensChecked, $cellsChecked, $identityChecks)
Write-Host ("  ours      {0} cells on hud.png, {1} strips covering every drawn row" -f $oursCells, $screens.ours.strips.Count)
Write-Host ("  joins     {0} atlas_id references resolved" -f $joinCount)
foreach ($warning in $warnings) { Write-Host "  note      $warning" }
Write-Host ''

if ($failures.Count -eq 0) {
    Write-Host ("ui-palette.json and ui-screens.json agree with the art: {0} colours, {1} cells, {2} panels, {3} joins" -f
        ($paletteOk + $paletteRectMean), ($cellsChecked + $oursCells), ($screensChecked + $screens.ours.screens.Count), $joinCount)
    exit 0
}

Write-Host ("{0} check(s) failed:" -f $failures.Count)
foreach ($failure in $failures) { Write-Host "  $failure" }
Write-Error ("assets\ui\ui-palette.json and/or assets\ui\ui-screens.json disagree with the art in {0} place(s). Every line above names the entry, what was expected and what was found; re-measure and correct the file, do not edit the art to suit it." -f $failures.Count)
exit 1
