# Regenerates the "Index" block at the top of every root markdown document.
#
# A hand-written index of line numbers is the project's own commonest bug shape -
# a value kept somewhere other than the thing that owns it - so it is derived
# instead. Run this after any documentation edit:
#
#   powershell -NoProfile -File tools\index-docs.ps1
#   powershell -NoProfile -File tools\index-docs.ps1 -Check   # fails if stale
#
# The block is delimited by HTML comments so it can be replaced without touching
# anything around it, and it sits directly under the document's title so it is
# the first thing a reader meets.
#
# Reads with -Encoding UTF8 and writes with UTF8Encoding($false): a bare
# Get-Content reads BOM-less UTF-8 as Windows-1252 and writing back
# double-encodes the file, which the U+FFFD check cannot detect.

param([switch]$Check)

$ErrorActionPreference = 'Stop'

$root = Resolve-Path (Join-Path $PSScriptRoot '..')
$begin = '<!-- INDEX -->'
$finish = '<!-- /INDEX -->'

# How deep each document's index goes. The right depth is whatever level a
# reader actually looks things up by: milestones in TIMELINE are `###`, sections
# in RESEARCH are `##`, and a short document needs no more than its `##`s.
$depth = @{
    'ANIMATION.md'        = 2
    'ASSETS-REFERENCE.md' = 3
    'CLAUDE.md'           = 3
    'CRAFTABLE.md'        = 2
    'DECISIONS.md'        = 2
    'INTERFACE.md'        = 2
    'LESSONS.md'          = 2
    'RESEARCH.md'         = 2
    'START-HERE.md'       = 2
    'SYSTEM_MEMORY.md'    = 3
    'TEXTURING.md'        = 3
    'TIMELINE.md'         = 3
    'm23planning.md'      = 3
}

$stale = @()

foreach ($file in Get-ChildItem -Path $root -Filter *.md -File | Sort-Object Name) {
    $maxLevel = if ($depth.ContainsKey($file.Name)) { $depth[$file.Name] } else { 2 }
    $lines = @(Get-Content -Encoding UTF8 $file.FullName)

    # Where the block goes: replacing an existing one, else after the title and
    # the paragraph that follows it, so the opening sentence still reads first.
    $blockStart = [Array]::IndexOf($lines, $begin)
    $blockEnd = [Array]::IndexOf($lines, $finish)
    if (($blockStart -lt 0) -ne ($blockEnd -lt 0)) { throw "$($file.Name): only one index marker" }

    # The block owns the blank line under its closing marker. Leaving it behind
    # would put a second one there on every run, so the file would grow by a
    # line each time and -Check could never report clean.
    $stripTo = $blockEnd
    if ($blockEnd -ge 0 -and $blockEnd + 1 -lt $lines.Count -and $lines[$blockEnd + 1] -eq '') { $stripTo++ }

    # Headings are counted against the FINAL line numbers, so the block's own
    # height has to be known before they can be worked out. Build it once
    # against the document with any old block removed, then correct by the
    # difference - which converges immediately because the entry count does not
    # depend on the offset.
    $body = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($blockStart -ge 0 -and $i -ge $blockStart -and $i -le $stripTo) { continue }
        $body.Add($lines[$i])
    }

    # Insertion point: after the first heading and the blank line under it.
    $insertAt = 0
    for ($i = 0; $i -lt $body.Count; $i++) {
        if ($body[$i] -match '^# ') { $insertAt = $i + 1; break }
    }
    while ($insertAt -lt $body.Count -and $body[$insertAt] -eq '') { $insertAt++ }

    $headings = New-Object System.Collections.Generic.List[object]
    $fenced = $false
    for ($i = 0; $i -lt $body.Count; $i++) {
        $line = $body[$i]
        # A `#` inside a fenced code block is a comment, not a heading.
        if ($line -match '^\s*```') { $fenced = -not $fenced; continue }
        if ($fenced) { continue }
        if ($line -match '^(#{1,6}) (.+)$') {
            $level = $Matches[1].Length
            if ($level -ge 1 -and $level -le $maxLevel) {
                $headings.Add([PSCustomObject]@{ Level = $level; Text = $Matches[2].Trim(); Row = $i })
            }
        }
    }

    $header = @(
        $begin,
        '',
        ('**Index** - ' + $headings.Count + ' sections. Line numbers, so a reader can jump straight there.'),
        '**Generated by `tools/index-docs.ps1`; do not hand-edit. Re-run it after editing this file.**',
        ''
    )
    $footer = @('', $finish, '')
    # The heights of the two halves are fixed, so every heading below the block
    # shifts by exactly this much.
    $shift = $header.Count + $headings.Count + $footer.Count

    $entries = New-Object System.Collections.Generic.List[string]
    foreach ($h in $headings) {
        $row = $h.Row + 1
        if ($h.Row -ge $insertAt) { $row += $shift }
        $indent = '  ' * ([Math]::Max(0, $h.Level - 1))
        $entries.Add(('{0}- **{1}** &middot; {2}' -f $indent, $row, $h.Text))
    }

    $block = $header + $entries.ToArray() + $footer

    $result = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $insertAt; $i++) { $result.Add($body[$i]) }
    foreach ($line in $block) { $result.Add($line) }
    for ($i = $insertAt; $i -lt $body.Count; $i++) { $result.Add($body[$i]) }

    $existing = @(Get-Content -Encoding UTF8 $file.FullName)
    $same = $existing.Count -eq $result.Count
    if ($same) {
        for ($i = 0; $i -lt $existing.Count; $i++) {
            if ($existing[$i] -ne $result[$i]) { $same = $false; break }
        }
    }

    if ($same) {
        Write-Host ('{0,-22} {1,4} sections  up to date' -f $file.Name, $headings.Count)
        continue
    }

    if ($Check) {
        $stale += $file.Name
        Write-Host ('{0,-22} {1,4} sections  STALE' -f $file.Name, $headings.Count)
        continue
    }

    $utf8 = New-Object System.Text.UTF8Encoding($false)
    [System.IO.File]::WriteAllLines($file.FullName, $result.ToArray(), $utf8)
    Write-Host ('{0,-22} {1,4} sections  written' -f $file.Name, $headings.Count)
}

if ($Check -and $stale.Count -gt 0) {
    Write-Error ('index out of date in: ' + ($stale -join ', '))
    exit 1
}
