#pragma once

#include <cstdint>

namespace game {

/// Smooth, repeatable pseudo-randomness.
///
/// Everything here is a pure function of its arguments and uses integer hashing
/// rather than any floating-point random source, so the same seed and position
/// give bit-identical results on any machine, compiler or thread. That property
/// is what makes a world reproducible from a single number.
namespace noise {

/// Value noise in the range [0, 1]. Nearby positions give similar results, which
/// is what separates this from plain randomness.
float value2D(std::uint32_t seed, float x, float z);

/// Several octaves of `value2D` summed, each at double the frequency and half
/// the strength. One octave is smooth blobs; four or five gives large landforms
/// with believable finer detail on top. Returns [0, 1].
float fbm2D(std::uint32_t seed, float x, float z, int octaves);

/// Value noise in three dimensions, [0, 1]. Needed for anything that varies with
/// height as well as position — caves and overhangs cannot come from a heightmap.
float value3D(std::uint32_t seed, float x, float y, float z);

/// Octaves of `value3D`, same rules as `fbm2D`. Returns [0, 1].
float fbm3D(std::uint32_t seed, float x, float y, float z, int octaves);

/// Octaved value noise in roughly [-1, 1], centred on zero.
///
/// `amplitudes[i]` weights the octave running at `2^i` times the base
/// frequency, and **a zero entry drops that octave outright** — which is how
/// the reference leaves deliberate holes in a spectrum instead of always
/// halving. Continentalness is `{1,1,2,2,2,1,1,1,1}` and temperature is
/// `{1.5,0,1,0,0,0}`; neither is expressible as "n octaves".
///
/// The sum divides out, so editing the array changes the *shape* of the field
/// and never its range.
float octaves2D(std::uint32_t seed, float x, float z, const float* amplitudes, int count);

/// `octaves2D` in three dimensions. Same range, same normalisation.
float octaves3D(std::uint32_t seed, float x, float y, float z, const float* amplitudes, int count);

/// Raw integer hash of a grid cell, for decisions that must be discrete rather
/// than smooth — whether a tree stands in this cell, and where in it.
std::uint32_t hash2D(std::uint32_t seed, std::int32_t x, std::int32_t z);

/// `hash2D` mapped to [0, 1).
float hashUnit2D(std::uint32_t seed, std::int32_t x, std::int32_t z);

/// A discrete roll at a block position, [0, 1).
///
/// Deliberately *not* smooth: the bedrock and deepslate bands are the one place
/// the reference uses a genuine per-block dice roll rather than a noise field,
/// and using noise there gives a wandering contour instead of a ragged edge.
float hashUnit3D(std::uint32_t seed, std::int32_t x, std::int32_t y, std::int32_t z);

/// A repeatable stream of rolls, seeded from a hash.
///
/// **Anything generated by more than one chunk must draw from one of these and
/// draw in the same order every time.** A tree or an ore vein straddling a chunk
/// border is built once per chunk it touches, and the copies have to agree block
/// for block — which they do only if the stream is re-seeded from the feature's
/// own cell and every draw happens whether or not the result lands in this
/// chunk.
struct Stream {
    std::uint32_t state;

    explicit Stream(std::uint32_t seed) : state(seed == 0u ? 0x9e3779b9u : seed) {}

    std::uint32_t next() {
        state ^= state << 13;
        state ^= state >> 17;
        state ^= state << 5;
        return state;
    }

    /// `0 .. n-1`.
    int range(int n) {
        return n <= 1 ? 0 : static_cast<int>(next() % static_cast<std::uint32_t>(n));
    }

    float unit() { return static_cast<float>(next() >> 8) / 16777216.0f; }
};

} // namespace noise
} // namespace game
